### ISSUE TITLE
[Nomination] giansalex for telegram bot

### ISSUE THREAD

**Issue by Highlander-maker** [CosmosContracts/hack-juno#15] opened 2021-08-02 12:07 UTC
Who are you nominating? 
@giansalex (Giancarlos Salas) 

What are you nominating them for?
His incredible work on Juno Telegram Bot and creation of the code that allows a user to upload a wasm file on chain

Please provide links to their work.
https://github.com/Highlander-maker/juno-tg-bot

**Comment by JakeHartnell** [comment] 2021-08-02 18:38
Nice. Would be cool if it supported token gated groups. I.E. own a certain amount of cw20 tokens to gain access to a telegram group.

**Comment by Highlander-maker** [comment] 2021-08-02 20:18
interesting... So smart contract  that checks the balance of a wallet that knows how much of the token that can gain access ?

**Comment by JakeHartnell** [comment] 2021-08-02 20:57
> interesting... So smart contract that checks the balance of a wallet that knows how much of the token that can gain access ?

You shouldn't need to write any custom smart contact. Can be handled entirely by the bot. Basically, have the user connect their wallet, get the balance from the cw20 token contract. If the user's amount is larger than the minimum set in bot config, then they get access to the token gated channel.

**Comment by nullmames** [comment] 2021-08-02 21:22
you should have also nominated yourself @Highlander-maker. you have spent a great amount of time on the project and started it also. @JakeHartnell

**Comment by Highlander-maker** [comment] 2021-08-02 22:23
ok Jake. Let me look in to it. :)

**Comment by blockcreators** [comment] 2021-08-03 11:44
@JakeHartnell pretty sure omniflix have this working already for telegram: juno.omniflix.com

**Comment by JakeHartnell** [comment] 2021-08-03 16:54
> @JakeHartnell pretty sure omniflix have this working already for telegram: juno.omniflix.com

If they open source it, will nominate them. They deserve some $JUNO for that. Does theirs work with cw20s?

**Comment by nullmames** [comment] 2021-08-03 20:18
This sounds like https://collab.land/

**Comment by JakeHartnell** [comment] 2021-09-30 20:03
@giansalex has been one of the most outstanding contributors during Hack Juno. :clap: :clap: :clap:

This ticket is a duplicate of his main nomination #13. So closing, but will link to this issue from there.

**Closed by JakeHartnell** 2021-09-30 20:03 UTC
Labels: Nomination
