### ISSUE TITLE
[Nomination] Again validator web34ever! He is unstoppable!

### ISSUE THREAD

**Issue by Antropocosmist** [CosmosContracts/hack-juno#35] opened 2021-09-20 21:40 UTC
**Who are you nominating?**

Validator web34ever - https://t.me/HeKit  <br />

**What are you nominating them for?**

For the creating of russian translation of "Smart Contract ERC20 Tutorial on Juno testnet"  - Инструкция по созданию Смарт контракта ERC20 в Juno testnet lucina <br />

It really helps to russian-speaking developers and not only to deploy smart-contract on Juno Network, and bring more decentralization to the Network by involving in the process people who don't speak english very good. It's a big value for the community! <br />

**Please provide links to their work.**

https://github.com/cybernekit/JunoSmartContract/blob/main/READMERUS.md

**Comment by JakeHartnell** [comment] 2021-09-20 22:48
If you have multiple entries for the same person, please put them all in the same ticket. Makes it easier to review. THANKS.

**Comment by Antropocosmist** [comment] 2021-09-22 08:59
I will try, but the problem, that people do something for Juno at the different time.
Do I need to edit my previous nominations?

**Comment by JakeHartnell** [comment] 2021-09-22 16:47
> I will try, but the problem, that people do something for Juno at the different time.
> Do I need to edit my previous nominations?

No need to edit the previous one, just keep in mind for the future. : )
You can always edit or add comments to the previous nominations.

**Comment by JakeHartnell** [comment] 2021-09-25 18:16
Duplicate of #34

**Closed by JakeHartnell** 2021-09-25 18:16 UTC
Labels: Nomination
