### ISSUE TITLE
[Nomination]

### ISSUE THREAD

**Issue by Highlander-maker** [CosmosContracts/hack-juno#25] opened 2021-09-13 18:47 UTC
**Who are you nominating?**
@the-frey 

**What are you nominating them for?**
there clear documentation not only for Cosmovisor but all the other content he has contributed his time to. 

**Please provide links to their work.**
https://docs.junochain.com/validators/setting-up-cosmovisor

**Comment by JakeHartnell** [comment] 2021-09-30 20:14
A great nomination! Closing as a duplicate of: #9

**Closed by JakeHartnell** 2021-09-30 20:14 UTC
Labels: Nomination
