### ISSUE TITLE
Highlander-Maker [Nomination]

### ISSUE THREAD

**Issue by Highlander-maker** [CosmosContracts/hack-juno#27] opened 2021-09-17 18:15 UTC
**Who are you nominating?**
@Highlander-maker 

**What are you nominating them for?**

Contribution to 4 projects which are still being developed further so i will update as i go along. Im not a prolific coder. Im not looking to blag Juno. i just want to highlight the time and effort to learn and hopefully contribute to this amazing community and highlight the amazing work put in by @giansalex .. Without him none of 3 of these project would even be on this list so thank you. Thank you to @JakeHartnell  @the-frey @nullmames @jackzampolin @dimiandre  for their help. Also, with out a doubt @Wolfcontract @blockcreators and not forgetting @toschdev for showing me the door to Cosmos eco-system. I am now have a basic toolset and knowledge to go forward and perform in future developments now. :). So thank you very much. 

Here is what ive been working on to date. 

1. Juno Telegram Bot
This bot has the ability to upload a compiled byte code on Juno chain. (Needs server to run on but npm you can run it locally). Gianny helped with linking this code to work on Juno. 

https://github.com/Highlander-maker/juno-tg-bot

2. Cosmwasm IDE ( writing suggestions for IDE and the use on Juno network as a ETH user on Remix)
Helped Orkin with a script on what to have in the IDE with my remix experience. As a user of this in the past coding projects on ETH Orkin was after more of what executional functions were required for deploying contracts on chain. (JUNO) 

https://github.com/CosmWasm/InterWasmDAO/pull/6

3. Work on Cosmverse (in progress) @giansalex big input on this. (STILL DEVELOPING)

https://github.com/CosmosContracts/cosmverse

4. CoinFlip Dapp
Simple betting app game linked on Juno network. Bet 50/50 your Juno for the chance to double up. @giansalex and myself wrote the code. i did it in Solidity while he re wrote in to Rust with the use of CW20

https://github.com/Highlander-maker/CoinFlipDapp

**Comment by nullmames** [comment] 2021-09-21 08:12
will be great to see these on mainnet. keep grinding mate.

**Comment by Highlander-maker** [comment] 2021-09-21 08:44
thanks a million @nullmames much appreciated. i am aiming to finish the TG bot my self so at least it is completed.

**Comment by JakeHartnell** [comment] 2021-09-30 20:19
Closing as duplicate of #14. Great job being a part of the community.

**Closed by JakeHartnell** 2021-09-30 20:19 UTC
Labels: Nomination
